### PR TITLE
fix(ios-publish): accept body on http post and update to new api

### LINKED ISSUE #5553: iTunesConnect API needs to be updated
**Environment**
 - CLI: 8.0.1
 - Cross-platform modules: N/A
 - Android Runtime: N/A
 - iOS Runtime: N/A
 - XCode Version: 12.5.1
 - Plugin(s): N/A

**Describe the bug**
cli commands that require connecting with iTunesConnect, such as publishing an iOS app, fails. The cli tries to call this URL:

https://appstoreconnect.apple.com/WebObjects/iTunesConnect.woa/ra/v1/session/webSession

which now throws a 404.

**To Reproduce**
Publish the app to the apple store, or execute any command that interacts with the AppStoreConnect API.
Example:
> ns publish ios
> ns appstore 

**Expected behavior**
Running "ns publish ios" should upload the ipa file successfully to TestFlight.

**Additional context**
This worked around early July, 2021, and broke recently. Apple may have deprecated the API.

**work around**
Run the Xcode upload command directly in Terminal after the ipa file is generated:

> xcrun altool --upload-app -f <PathToFile>.ipa -u <Username> -p <Password>

### PR DESCRIPTION
**Pull request by jcassidyav**
## PR Checklist

- [X] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [X] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [ ] You have signed the [CLA](http://www.nativescript.org/cla).
- [X] All existing tests are passing: https://github.com/NativeScript/nativescript-cli/blob/master/CONTRIBUTING.md#contribute-to-the-code-base
- [ ] Tests for the changes are included.

## What is the current behavior?
With 8.1 cli ```ns publish ios``` resulted in 401
In previous cli versions it resulted in 404 because the endpoint for changing the team was removed by apple.

## What is the new behavior?
```ns publish ios --appleApplicationSpecificPassword ...``` 
```ns appstore```

now both work.

Fixes/Implements/Closes #5553.

### CODE REVIEW

File: lib/common/http-client.ts [hunk 1]
```diff
@@ -107,12 +107,20 @@ export class HttpClient implements Server.IHttpClient {
...
+			data = options.body;
+		}
+
 		const result = await axios({
 			url: options.url,
 			headers: options.headers,
 			method: options.method,
 			proxy: false,
 			httpAgent: agent,
+			data: data,
```
Comment (rigor789) [inline lib/common/http-client.ts:123]:
```suggestion
			data: options.body,
```

File: lib/common/http-client.ts [hunk 2]
```diff
@@ -107,12 +107,20 @@ export class HttpClient implements Server.IHttpClient {
 				},
 			});
 		}
+
+		let data;
+
+		if (options.body) {
+			data = options.body;
+		}
+
```
Comment (rigor789) [inline lib/common/http-client.ts:116]:
```suggestion
```

**Review by rigor789 — APPROVED** [review]
lgtm, just small change to simplify logic in http-client

**Review by rigor789 — APPROVED** [review]
