### PR TITLE
fix: read npm registry from npm config

### LINKED ISSUE #3866: Read registry from npm config instead of hard-wiring to npmjs.org in node-package-manager
We use artifactory as a our internal npm repository. It mirrors npmjs.org and also allow us to push internal npm packages to it.

However, when we do a clean install/build using `tns build android` the nativescript-cli itself starts a http client to pull the tns-android package from npmjs.org:

https://github.com/NativeScript/nativescript-cli/blob/f0e150ca8b2988bb23caafa2e239ee91cc8cde14/lib/node-package-manager.ts#L123

this does not work for us. 

Ideally, inside the `getRegistryPackageData` the registry to use should be read from the npm config (.npmrc)

### PR DESCRIPTION
**Pull request by lambourn**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/nativescript-cli/blob/master/CONTRIBUTING.md#contribute-to-the-code-base
- [ ] Tests for the changes are included.

## What is the current behavior?

nativescript-cli assumes that npmjs.org is used. If another (local) repo like artifactory is used, `tns add platform` (and probably other steps) fails as it hard-wired tries to pull packages from npmjs.org

## What is the new behavior?

read npm registry from npm config instead of hard-wiring it to npmjs.org, fixes #3866

### CODE REVIEW

**Comment by rosen-vladimirov** [comment]
run ci

File: lib/node-package-manager.ts [hunk 1]
```diff
@@ -120,7 +120,8 @@ export class NodePackageManager implements INodePackageManager {
 	}
 
 	public async getRegistryPackageData(packageName: string): Promise<any> {
-		const url = `https://registry.npmjs.org/${packageName}`;
+		const registry = await this.$childProcess.exec(`npm config get registry`);
```
Comment (rosen-vladimirov) [inline lib/node-package-manager.ts]: What do you think about falling back to registry.npmjs.org in case `npm config get registry` fails for some reason?
For example:
```TypeScript
let registry = "https://registry.npmjs.org/";
try {
    registry = await this.$childProcess.exec(`npm config get registry`);
} catch (err) {
    this.$logger.trace("Unable to get information for current npm registry", err);
}

const url = registry.trim() + packageName;
```

Comment (lambourn) [reply lib/node-package-manager.ts]: I thought about this as well - defensive programming FTW ;-) But even if I wipe my `.npmrc` file, the value npm defaults to is always `https://registry.npmjs.org/`

Comment (rosen-vladimirov) [reply lib/node-package-manager.ts]: Ok, thanks for the explanation. We'll run our tests now and if the build is green, I'll merge this PR.

**Comment by rosen-vladimirov** [comment]
@lambourn thanks a lot for your Contribution! We've merged the suggested fix and it will be included in our 5.0.0 release. The fix will be available soon in CLI's next version - you can install it by executing `npm i -g nativescript@next` (it may take 15-20 minutes to publish the next version with the fix).
