### PR TITLE
Fix IPA export

### LINKED ISSUE #3020: iOS Archive Export unexpected behavior when using AdHoc or AppStore provisioning
From Xcode 8.3+ the way IPA is built changed.
The generation of the IPA is a two step process now:
 1. `xcodebuild archive`
 2. `xcodebuild export`

#### Archive
This makes an archive folder that has app, debug symbols, etc. It has all the artefacts necessary to export for Development, Ad-Hoc or App Store distribution. The app is signed with the certificate and provisioning profiles set in the .xcconfig or in the xcodeproj (using the --provision option).

#### Export
This takes the archive and exports IPA for Development, Ad-Hoc or AppStore. During the export, the app is often resigned with a distribution certificate and an ad-hoc or AppStore distribution provisioning profile.

## Problems
Currently the CLI does archive then export for development when `tns build|run` is issued. This leads to underwhelming results when developers try to publish at the store or export for ad-hoc using `tns build`. Why? During the export session the xcodebuild command accepts an `-exportOptionsPlist` that can contain keys listed in [`xcodebuild --help`](https://gist.github.com/PanayotCankov/3c81cf106c8b7bb5efa3ad05d9731abe). Most importantly the: `method : String`:

> Describes how Xcode should export the archive. Available options: app-store, package, ad-hoc, enterprise, development, and developer-id. The list of options varies based on the type of archive. Defaults to development.

The default is "development", for exportOptionsPlist currently the app/App_Resources/Info.plist is currently provided (IMO incorrectly) and it has no `method` key, so `development` is used as fallback. When the developers configure the .xcconfig to use Ad-Hoc or AppStore provisioning profile, the export is still performed as development, the result IPA is then incorrectly set to still use development settings such as entitlements.

Here are the related issues to exactly this problem:
 - https://github.com/NativeScript/nativescript-cli/issues/2888
 - https://github.com/NativeScript/nativescript-cli/issues/2999 
    (perhaps incorrectly?) tries to provide distribution certificate for archive, while archive should be performed with development certificate and export should sign with distribution certificate
 - https://github.com/NativeScript/nativescript-cli/issues/2922
    Signes multitarget app with the AppStore distribution, there is a bug in old Ruby and Cocoapods that leads to this
 - https://github.com/NativeScript/nativescript-cli/issues/2888
    Building with --release as mentioned still exports with method: development
 - https://github.com/NativeScript/nativescript-cli/issues/2716
 - https://github.com/NativeScript/nativescript-cli/issues/2702
    Similar to 2922 - resolved by ruby and cocoapods update but also the missing exportOptionsPlist is noted in warnings

We have discussed internally that adding `tns archive` + `tns export` would diverge too much from the current and Android build commands, also people shouldn't care how the build is implemented internally.

Here are some clues how this can be addressed:
The export during `tns build ios` is done here:
https://github.com/NativeScript/nativescript-cli/blob/1955028ac3ded6a012813476f08d0f4f0d89dddd/lib/services/ios-project-service.ts#L259-L263
It incorrectly gets the app/App_Resources/Info.plist as exportOptionsPlist. Instead such export.plist files should be generated somewhere in the platforms/ios/build similar to the exportArchive that is currently used only for distribution:
https://github.com/NativeScript/nativescript-cli/blob/1955028ac3ded6a012813476f08d0f4f0d89dddd/lib/services/ios-project-service.ts#L212-L229
The method - Ad-Hoc or AppStore distribution that should be used during `tns build ios` should either be provided through an option, or inferred from the provisioning profile used during the build.

### PR DESCRIPTION
**Pull request by PeterStaev**
Fixes #3020 and related issues by reading the `embedded.mobileprovision` from the built `.app`, detecting the type of the provision that is used and then sending the correct export method when exporting the `.ipa`

### CODE REVIEW

**Comment by dtopuzov** [comment]
run ci

File: lib/services/ios-project-service.ts [hunk 1]
```diff
@@ -1312,6 +1326,32 @@ We will now place an empty obsolete compatability white screen LauncScreen.xib f
...
+	private async getEmbeddedPlistData(projectData: IProjectData): Promise<IDictionary<any>> {
+		let embeddedPlistContents = "";
+		const embeddedMobileProvisionPath = path.join(this.getPlatformData(projectData).deviceBuildOutputPath, `${projectData.projectName}.app`, "embedded.mobileprovision");
+
+		embeddedPlistContents = await this.$childProcess.exec(`security cms -D -i ${embeddedMobileProvisionPath}`);
+
+		return plist.parse(embeddedPlistContents);
+	}
+
+	private async getExportOptionsMethod(projectData: IProjectData): Promise<"app-store" | "ad-hoc" | "enterprise" | "development"> {
```
Comment (PanayotCankov) [inline lib/services/ios-project-service.ts]: Working with provisioning profiles.
This belongs to the https://github.com/NativeScript/nativescript-cli/blob/master/lib/services/ios-provision-service.ts#L9
Add a method there that by given path the mobileprovision can be read.

Comment (PanayotCankov) [inline lib/services/ios-project-service.ts]: Extract this block:
https://github.com/NativeScript/ios-mobileprovision-finder/blob/master/index.ts#L88
onto a "read from file" function and export that function in the ios-mobileprovision-finder
Use it instead of plist parse to obtain the information about the mobileprovision,
If necessary fix/extend the type here: https://github.com/NativeScript/ios-mobileprovision-finder/blob/master/index.ts#L101
then map that type to mode in the current method.

**Comment by dtopuzov** [comment]
run ci

**Comment by vbresults** [comment]
Isn't exportOptions.plist included in the new App_Resources iOS template and copied during the prepare step?  Why are we creating a temporary one here?

**Comment by PanayotCankov** [comment]
@vbresults I don't think they are, or at least I haven't noticed. I don't see them here:
https://github.com/NativeScript/template-hello-world/tree/master/App_Resources/iOS
Imo @PeterStaev is on the right track. Just the code should be reorganised. And if possible reused with the existing stuff in the provision service.

**Comment by PeterStaev** [comment]
@vbresults I do not see those being used in the CLI code even if they are added to the template, but I also do not see it there. Also it does not make sense to make them part of the template as those options change depending on the build/provision type.

File: lib/services/ios-project-service.ts (hunk 1 above)
Comment (PanayotCankov) [inline lib/services/ios-project-service.ts]: Just disable the bitcode:
```
    <key>uploadBitcode</key>
    <false/>
```
later, if it is necessary, we may add flags to specify path to a custom plist file.

**Comment by vbresults** [comment]
I feel like hardcoding will cause problems again, the way it did the first time, leading to this PR.  Why not put in a regular plist variable `${EXPORT_METHOD}` and then replace it during the prepare step?

We could have it as part of the `tns-ios` project template by default, and if defined in `App_Resources` it overwrites with that; this helps avoid surprises later or imposing decisions made.

p.s. Turns out that I edited that script to use my exportOptions.plist.

**Comment by PanayotCankov** [comment]
This is good to go: https://www.npmjs.com/package/ios-mobileprovision-finder 1.0.10

File: lib/services/ios-project-service.ts [hunk 2]
```diff
@@ -1312,6 +1328,18 @@ We will now place an empty obsolete compatability white screen LauncScreen.xib f
 		}
 		return teamId;
 	}
+
+	private getExportOptionsMethod(projectData: IProjectData): string {
+		const embeddedMobileProvisionPath = path.join(this.getPlatformData(projectData).deviceBuildOutputPath, `${projectData.projectName}.app`, "embedded.mobileprovision");
+		const provision = mobileprovision.provision.readFromFile(embeddedMobileProvisionPath);
+
+		return {
```
Comment (PanayotCankov) [inline lib/services/ios-project-service.ts]: I love this way of mapping big time!
Definitely better than switches!

**Comment by dtopuzov** [comment]
run ci

**Comment by PanayotCankov** [comment]
I just resolved a trivial merge conflict.

File: lib/services/ios-project-service.ts (hunk 2 above)
Comment (PeterStaev) [inline lib/services/ios-project-service.ts]: Actually took the idea from the `ios-mobileprovision-finder` 😄

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
@PanayotCankov before we get QAs on this we should fix Travis and Jenkins checks.

Currently builds fails with:
```
[33mCompiling...[39m
Using tsc v2.4.1
lib/services/ios-project-service.ts(1336,47): error TS2339: Property 'readFromFile' does not exist on type 'typeof provision'.
lib/services/ios-project-service.ts(1338,10): error TS7017: Element implicitly has an 'any' type because type '{ "Development": string; "AdHoc": string; "Distribution": string; "Enterprise": string; }' has no index signature.
```

**Comment by PeterStaev** [comment]
@dtopuzov , for some reason the CI build does not install the new version of `ios-mobileprovision-finder` and the package continues to be 1.0.9 instead of 1.0.10: https://travis-ci.org/NativeScript/nativescript-cli/builds/262575088#L720. Not sure why as in the `package.json` I've put the new version.

**Comment by rosen-vladimirov** [comment]
@PeterStaev , this is due to the existence of `shrinkwrap` file in the repository. I can help you to resolve this issue by regenerating the shrinkwrap in a separate commit.

**Comment by PeterStaev** [comment]
That would be great @rosen-vladimirov ! I've tried regenerating it using `npm shrinkwrap` but the new file is totally different...

**Comment by rosen-vladimirov** [comment]
run ci

**Comment by rosen-vladimirov** [comment]
@PeterStaev I've updated the shrinkwrap json (in fact I've removed the ios-mobileprovision-finder from package.json and executed `npm install --save --save-exact ios-mobileprovision-finder@1.0.10` with npm5. This updated only this entry in the shrinkwrap file.
I've also rebased your branch on latest master, so I had to push force it, please excuse me for this.

The functional tests are running and we'll see the results ;)

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by vbresults** [comment]
How much time before this is available in @next?

**Comment by dtopuzov** [comment]
I hope it will be live later today :)

**Comment by rosen-vladimirov** [comment]
Hey @PeterStaev ,  we've merged this PR. Thanks again for your great contribution.

@vbresults this change is already available in `@next` of CLI.
