### PR TITLE
fix: xcode10 build

### LINKED ISSUE #3723: iOS build for device fails with Xcode 10 beta 2
### Tell us about the problem
iOS builds for device fail with Xcode 10 beta 2.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: latest
- Cross-platform modules: latest
- Runtime(s): latest
- Plugin(s): No

### Please tell us how to recreate the issue in as much detail as possible.
```
npm i -g nativescript
tns create TestApp
tns build ios --release --for-device --path TestApp
```

### PR DESCRIPTION
**Pull request by dtopuzov**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/nativescript-cli/blob/master/CONTRIBUTING.md#contribute-to-the-code-base
- [ ] Tests for the changes are included.

## What is the current behavior?
`tns build ios --release --for-device` fails with Xcode 10 beta 2.

## What is the new behavior?
This PR should fix it.

Fixes #3723.

### CODE REVIEW

File: lib/services/ios-project-service.ts [hunk 1]
```diff
@@ -257,6 +257,8 @@ export class IOSProjectService extends projectServiceBaseLib.PlatformProjectServ
 		plistTemplate += `    <key>method</key>
     <string>app-store</string>
     <key>uploadBitcode</key>
+	<false/>
```
Comment (rosen-vladimirov) [inline lib/services/ios-project-service.ts]: can you please fix the indentation wherever you've added the new keys
